language: php
php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev --no-interaction
script:
  - make lint
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
after_script:
  - php vendor/bin/coveralls
    # or enable logging
  - php vendor/bin/coveralls -v
